---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd" #yum install httpd (to install apache server) - httpd automatically understands that its apache
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
